CursoMVC/Models/inscripcion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CursoMVC.Models
{
   /* public enum Nota

    {

        A, B, C, D, F

    }*/
    public class Inscripcion
    {
        [Key]
        public int InscripcionID { get; set; }

        [Required(ErrorMessage = "El valor es obligatorio")]
        [Display(Name = "Fecha de inscripción")]
        public DateTime FechaDeInscripcion { get; set; }

        [Display(Name = "Curso")]
        public int CursoID { get; set; }
        [Display(Name = "DNI")]
        public int AlumnoID { get; set; }
        [Display(Name = "Nota")]
        public int NotaID { get; set; }
        [Display(Name = "Apellidos")]
        public int AlumnoApellidos { get; set; }
        [Display(Name = "Nombre")]
        public string AlumnoNombre { get; set; }
       public string calificacion { get; set; }
        public Nota Nota { get; set; }

        public Curso Curso { get; set; }

        public Alumno Alumno { get; set; }
    }
}

CursoMVC/Controllers/InscripcionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursoMVC.Data;
using CursoMVC.Models;

namespace CursoMVC.Controllers
{
    public class InscripcionController : Controller
    {
        private readonly Contexto _context;

        public InscripcionController(Contexto context)
        {
            _context = context;
        }

        // GET: Inscripcion
        public async Task<IActionResult> Index(string busquedaNota, string busquedaPorAlumno, string busquedaPorCurso)
        {
            var v_inscripciones = from m in _context.Inscripciones
                                  select m;
            v_inscripciones = _context.Inscripciones.Include(i => i.Alumno).Include(i => i.Curso).Include(i => i.Nota);
            if(!String.IsNullOrEmpty(busquedaNota))
            {
                v_inscripciones = v_inscripciones.Where(n => n.Nota.calificacion.Contains(busquedaNota));
            }
            if(!String.IsNullOrEmpty(busquedaPorAlumno))
            {
                v_inscripciones = v_inscripciones.Where(a => a.Alumno.AlumnoDNI.Contains(busquedaPorAlumno));
            }
            if(!String.IsNullOrEmpty(busquedaPorCurso))
            {
                v_inscripciones = v_inscripciones.Where(c => c.Curso.Titulo.Contains(busquedaPorCurso));
            }
            return View(await v_inscripciones.ToListAsync());
        }

        // GET: Inscripcion/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscripcion = await _context.Inscripciones
                .Include(i => i.Alumno)
                .Include(i => i.Curso)
                .Include(i => i.Nota)
                .FirstOrDefaultAsync(m => m.InscripcionID == id);
            if (inscripcion == null)
            {
                return NotFound();
            }

            return View(inscripcion);
        }

        // GET: Inscripcion/Create
        public IActionResult Create()
        {
            ViewData["AlumnoID"] = new SelectList(_context.Alumnos, "AlumnoID", "AlumnoDNI","AlumnoNombre", "AlumnoApellidos");
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "Titulo");
            ViewData["NotaID"] = new SelectList(_context.Notas, "NotaID", "calificacion");
            return View();
        }

        // POST: Inscripcion/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InscripcionID,FechaDeInscripcion,CursoID,AlumnoID,NotaID,AlumnoApellidos,AlumnoNombre,calificacion")] Inscripcion inscripcion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inscripcion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AlumnoID"] = new SelectList(_context.Alumnos, "AlumnoID", "AlumnoDNI", inscripcion.AlumnoID);
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "Titulo", inscripcion.CursoID);
            ViewData["NotaID"] = new SelectList(_context.Notas, "NotaID", "calificacion", inscripcion.NotaID);
            return View(inscripcion);
        }

        // GET: Inscripcion/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscripcion = await _context.Inscripciones.FindAsync(id);
            if (inscripcion == null)
            {
                return NotFound();
            }
            ViewData["AlumnoID"] = new SelectList(_context.Alumnos, "AlumnoID", "AlumnoDNI",  inscripcion.AlumnoID);
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "Titulo", inscripcion.CursoID);
            ViewData["NotaID"] = new SelectList(_context.Notas, "NotaID", "calificacion", inscripcion.NotaID);
            return View(inscripcion);
        }

        // POST: Inscripcion/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InscripcionID,FechaDeInscripcion,CursoID,AlumnoID,NotaID,AlumnoApellidos,AlumnoNombre,calificacion")] Inscripcion inscripcion)
        {
            if (id != inscripcion.InscripcionID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inscripcion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InscripcionExists(inscripcion.InscripcionID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AlumnoID"] = new SelectList(_context.Alumnos, "AlumnoID", "AlumnoDNI", inscripcion.AlumnoID);
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "Titulo", inscripcion.CursoID);
            ViewData["NotaID"] = new SelectList(_context.Notas, "NotaID", "calificacion", inscripcion.NotaID);
            return View(inscripcion);
        }

        // GET: Inscripcion/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscripcion = await _context.Inscripciones
                .Include(i => i.Alumno)
                .Include(i => i.Curso)
                .Include(i => i.Nota)
                .FirstOrDefaultAsync(m => m.InscripcionID == id);
            if (inscripcion == null)
            {
                return NotFound();
            }

            return View(inscripcion);
        }

        // POST: Inscripcion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inscripcion = await _context.Inscripciones.FindAsync(id);
            _context.Inscripciones.Remove(inscripcion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InscripcionExists(int id)
        {
            return _context.Inscripciones.Any(e => e.InscripcionID == id);
        }
    }
}

CursoMVC/Views/Inscripcion/Create.cshtml
@model CursoMVC.Models.Inscripcion

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Inscripcion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaDeInscripcion" class="control-label"></label>
                <input asp-for="FechaDeInscripcion" class="form-control" />
                <span asp-validation-for="FechaDeInscripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class ="form-control" asp-items="ViewBag.CursoID"></select>
            </div>
            <div class="form-group">
                <label asp-for="AlumnoID" class="control-label"></label>
                <select asp-for="AlumnoID" class ="form-control" asp-items="ViewBag.AlumnoID"></select>
            </div>
            <div class="form-group">
                <label asp-for="NotaID" class="control-label"></label>
                <select asp-for="NotaID" class ="form-control" asp-items="ViewBag.NotaID"></select>
            </div>
            
           
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Inscripcion/Delete.cshtml
@model CursoMVC.Models.Inscripcion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inscripcion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeInscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDeInscripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoApellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoApellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.calificacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.calificacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota.NotaID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso.CursoID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alumno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alumno.AlumnoApellidos)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InscripcionID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CursoMVC/Views/Inscripcion/Details.cshtml
@model CursoMVC.Models.Inscripcion

@{
    ViewData["Title"] = "Details";
}

<h1 style="margin-bottom: 20px;">MAS INFORMACION</h1>

<div class="jumbotron">
    <h4 class="text-center">Inscripción</h4>
    <hr style="border: 2px solid;"/>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeInscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDeInscripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alumno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alumno.AlumnoDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoApellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alumno.AlumnoApellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alumno.AlumnoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota.calificacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso.Titulo)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.InscripcionID"><span class="glyphicon glyphicon-edit" style="color:forestgreen;"> </span></a>
    <a asp-action="Index" class="btn btn-info">REGRESAR A LA LISTA</a>
</div>

CursoMVC/Views/Inscripcion/Edit.cshtml
@model CursoMVC.Models.Inscripcion

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Inscripcion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InscripcionID" />
            <div class="form-group">
                <label asp-for="FechaDeInscripcion" class="control-label"></label>
                <input asp-for="FechaDeInscripcion" class="form-control" />
                <span asp-validation-for="FechaDeInscripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class="form-control" asp-items="ViewBag.CursoID"></select>
                <span asp-validation-for="CursoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlumnoID" class="control-label"></label>
                <select asp-for="AlumnoID" class="form-control" asp-items="ViewBag.AlumnoID"></select>
                <span asp-validation-for="AlumnoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotaID" class="control-label"></label>
                <select asp-for="NotaID" class="form-control" asp-items="ViewBag.NotaID"></select>
                <span asp-validation-for="NotaID" class="text-danger"></span>
            </div>
                       
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Inscripcion/Index.cshtml
@model IEnumerable<CursoMVC.Models.Inscripcion>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">LISTADO DE INSCIPCIONES</h1>

<p>
    <a asp-action="Create" class=" btn btn-success">AÑADIR INSCRIPCION</a>
</p>
<form asp-controller="Inscripcion" asp-action="Index">
    <div class="jumbotron">

        <p> <span class="glyphicon glyphicon-search"> </span>  Nota: <input type="text" name="busquedaNota" /></p>
        <p> <span class="glyphicon glyphicon-search"> </span>  DNI: <input type="text" name="busquedaPorAlumno" /></p>
        <p> <span class="glyphicon glyphicon-search"> </span>  Curso: <input type="text" name="busquedaPorCurso" /></p>
        <input type="submit" class="btn-info" value="Buscar Inscripción" />
    </div>
</form>
<table class="table , text-center" style="background-color:whitesmoke;margin-top:20px;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeInscripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlumnoApellidos)
            </th>
          
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDeInscripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alumno.AlumnoDNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alumno.AlumnoApellidos)
            </td>
           
            
            <td>
                @Html.DisplayFor(modelItem => item.Curso.Titulo)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.InscripcionID"><span class="glyphicon glyphicon-edit" style="color:forestgreen;"> </span></a> 
                <a asp-action="Details" asp-route-id="@item.InscripcionID"><span class="glyphicon glyphicon-info-sign" style="color:blue;"> </span></a> 
                <a asp-action="Delete" asp-route-id="@item.InscripcionID"><span class="glyphicon glyphicon-trash" style="color:red;"> </span></a>
            </td>
        </tr>
}
    </tbody>
</table>