CursoMVC/Models/Alumno.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CursoMVC.Models
{
    public class Alumno
    {
        [Key]
        public int AlumnoID { get; set; }
        [Required(ErrorMessage = "El valor es obligatorio")]
        [RegularExpression("^(([A-Z]\\d{8})|(\\d{8}[A-Z]))$", ErrorMessage = "DNI incorrecto")]
        [Display(Name = "DNI")]
        public string AlumnoDNI { get; set; }
        [Required(ErrorMessage = "El valor es obligatorio")]
        [Display(Name = "Apellidos")]
        public string AlumnoApellidos { get; set; }
        [Required(ErrorMessage = "El valor es obligatorio")]
        [Display(Name = "Nombre")]
        public string AlumnoNombre { get; set; }
                      
        public ICollection<Inscripcion> Inscripcion { get; set; }


    }
}

CursoMVC/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursoMVC.Data;
using CursoMVC.Models;

namespace CursoMVC.Controllers
{
    public class AlumnoController : Controller
    {
        private readonly Contexto _context;

        public AlumnoController(Contexto context)
        {
            _context = context;
        }

        // GET: Alumno
        public async Task<IActionResult> Index(string busquedaAlumnoDNI,string busquedaAlumno )
        {
            var v_alumnos = from a in _context.Alumnos
                            select a;
            //v_alumnos = _context.Alumnos.Include(p => p.Apellidos);
            if (!String.IsNullOrEmpty(busquedaAlumnoDNI))
            {
                v_alumnos = v_alumnos.Where(s => s.AlumnoDNI.Contains(busquedaAlumnoDNI));
            }
            if (!String.IsNullOrEmpty(busquedaAlumno))
            {
                v_alumnos = v_alumnos.Where(s => s.AlumnoApellidos.Contains(busquedaAlumno));
            }
            return View(await v_alumnos.ToListAsync());

        }

        // GET: Alumno/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumno = await _context.Alumnos
                .FirstOrDefaultAsync(m => m.AlumnoID == id);
            if (alumno == null)
            {
                return NotFound();
            }

            return View(alumno);
        }

        // GET: Alumno/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alumno/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlumnoID,AlumnoDNI,AlumnoApellidos,AlumnoNombre")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                var alumn = await _context.Alumnos
                    .FirstOrDefaultAsync(m => m.AlumnoDNI == alumno.AlumnoDNI);
                if(alumn == null)
                {
                    _context.Add(alumno);
                    await _context.SaveChangesAsync();
                    ViewData["result"] = "";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["result"] = "Ya existe DNI";
                }
               
            }
            return View(alumno);
        }

        // GET: Alumno/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumno = await _context.Alumnos.FindAsync(id);
            if (alumno == null)
            {
                return NotFound();
            }
            return View(alumno);
        }

        // POST: Alumno/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlumnoID,AlumnoDNI,AlumnoApellidos,AlumnoNombre")] Alumno alumno)
        {
            if (id != alumno.AlumnoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alumno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlumnoExists(alumno.AlumnoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alumno);
        }

        // GET: Alumno/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumno = await _context.Alumnos
                .FirstOrDefaultAsync(m => m.AlumnoID == id);
            if (alumno == null)
            {
                return NotFound();
            }

            return View(alumno);
        }

        // POST: Alumno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alumno = await _context.Alumnos.FindAsync(id);
            _context.Alumnos.Remove(alumno);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlumnoExists(int id)
        {
            return _context.Alumnos.Any(e => e.AlumnoID == id);
        }
    }
}

CursoMVC/Views/Alumno/Create.cshtml
@model CursoMVC.Models.Alumno

@{
    ViewData["Title"] = "Create";
}

<h1 style="margin-bottom: 20px;">AÑADIR ALUMNO</h1>


<hr />
<div class="row , jumbotron">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AlumnoDNI" class="control-label"></label>
                <input asp-for="AlumnoDNI" class="form-control" />
                <span asp-validation-for="AlumnoDNI" class="text-danger"></span>
                <p style="color:red; font-weight:bold"> @ViewData["result"]</p>
               
            </div>
            <div class="form-group">
                <label asp-for="AlumnoApellidos" class="control-label"></label>
                <input asp-for="AlumnoApellidos" class="form-control" />
                <span asp-validation-for="AlumnoApellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlumnoNombre" class="control-label"></label>
                <input asp-for="AlumnoNombre" class="form-control" />
                <span asp-validation-for="AlumnoNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="GUARDAR" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info" >REGRESAR A LA LISTA</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Alumno/Delete.cshtml
@model CursoMVC.Models.Alumno

@{
    ViewData["Title"] = "Delete";
}

<h1>ELIMINAR ALUMNO</h1>

<div class="jumbotron">

<h3 style="font-weight: bold; font-style: italic;" >¿ES SEGURO ELIMINAR EL ALUMNO?</h3>
<div>
   
    <hr  class="my-4" style="border: 2px solid ;"/>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoDNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoApellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoApellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoNombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AlumnoID" />
        <input type="submit" value="ELIMINAR" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-info">REGRESAR A LA LISTA</a>
    </form>
</div>
    </div>

CursoMVC/Views/Alumno/Details.cshtml
@model CursoMVC.Models.Alumno

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoDNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoApellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoApellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoNombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AlumnoID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CursoMVC/Views/Alumno/Edit.cshtml
@model CursoMVC.Models.Alumno

@{
    ViewData["Title"] = "Edit";
}

<h1 style="margin-bottom: 20px;">EDITAR ALUMNO</h1>


<hr />
<div class="row, jumbotron">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AlumnoID" />
            <div class="form-group">
                <label asp-for="AlumnoDNI" class="control-label"></label>
                <input asp-for="AlumnoDNI" class="form-control" />
                <span asp-validation-for="AlumnoDNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlumnoApellidos" class="control-label"></label>
                <input asp-for="AlumnoApellidos" class="form-control" />
                <span asp-validation-for="AlumnoApellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlumnoNombre" class="control-label"></label>
                <input asp-for="AlumnoNombre" class="form-control" />
                <span asp-validation-for="AlumnoNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="GUARDAR" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info" >REGRESAR A LA LISTA</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Alumno/Index.cshtml
@model IEnumerable<CursoMVC.Models.Alumno>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">LISTADO DE ALUMNOS</h1>

<p>
    <a asp-action="Create" class=" btn btn-success" >AÑADIR ALUMNO</a>
</p>
<form asp-controller="Alumno" asp-action="Index">
    <div class="jumbotron">
        <p><span class="glyphicon glyphicon-search"> </span>  DNI: <input type="text" name="busquedaAlumnoDNI" /></p>
        <p> <span class="glyphicon glyphicon-search"> </span>  Apellido: <input type="text" name="busquedaAlumno" /></p>
             
           
        
               
        <input type="submit" class="btn-info" value="Buscar Alumno" />
    </div>
</form>
<table class="table , text-center" style="background-color:whitesmoke;margin-top:20px;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlumnoDNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlumnoApellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlumnoNombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlumnoDNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlumnoApellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlumnoNombre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AlumnoID"><span class="glyphicon glyphicon-edit" style="color:forestgreen;"> </span></a> 
                @*<a asp-action="Details" asp-route-id="@item.AlumnoID">Details</a> |*@
                <a asp-action="Delete" asp-route-id="@item.AlumnoID"><span class="glyphicon glyphicon-trash" style="color:red;"> </span></a>
            </td>
        </tr>
}
    </tbody>
</table>