CursoMVC/Models/Docente.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CursoMVC.Models
{
    
    public class Docente
    {
        [Key]
        public int DocenteID { get; set; }
        [Required(ErrorMessage = "El valor es obligatorio")]
        [RegularExpression("^(([A-Z]\\d{8})|(\\d{8}[A-Z]))$", ErrorMessage = "DNI incorrecto")]
        [Display(Name = "DNI")]
        public string DocenteDNI { get; set; }

        [Display(Name = "Curso")]
        public int CursoID { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
       
        public Curso Curso { get; set; }
    }
}

CursoMVC/Controllers/DocenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursoMVC.Data;
using CursoMVC.Models;

namespace CursoMVC.Controllers
{
    public class DocenteController : Controller
    {
        private readonly Contexto _context;

        public DocenteController(Contexto context)
        {
            _context = context;
        }

        // GET: Docente
        public async Task<IActionResult> Index(string busquedaDocenteDNI, string busquedaDocente)
        {
            var v_docentes = from d in _context.Docentes
                             select d;
            v_docentes = _context.Docentes.Include(d => d.Curso);
            if(!String.IsNullOrEmpty(busquedaDocenteDNI))
            {
                v_docentes = v_docentes.Where(s => s.DocenteDNI.Contains(busquedaDocenteDNI));
            }

            if(!String.IsNullOrEmpty(busquedaDocente))
            {
                v_docentes = v_docentes.Where(n => n.Apellidos.Contains(busquedaDocente));
            }
            return View(await v_docentes.ToListAsync());
        }

        // GET: Docente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var docente = await _context.Docentes
                .Include(d => d.Curso)
                .FirstOrDefaultAsync(m => m.DocenteID == id);
            if (docente == null)
            {
                return NotFound();
            }

            return View(docente);
        }

        // GET: Docente/Create
        public IActionResult Create()
        {
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "CursoID");
            return View();
        }

        // POST: Docente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DocenteID,DocenteDNI,CursoID,Nombre,Apellidos")] Docente docente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(docente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "CursoID", docente.CursoID);
            return View(docente);
        }

        // GET: Docente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var docente = await _context.Docentes.FindAsync(id);
            if (docente == null)
            {
                return NotFound();
            }
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "CursoID", docente.CursoID);
            return View(docente);
        }

        // POST: Docente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DocenteID,DocenteDNI,CursoID,Nombre,Apellidos")] Docente docente)
        {
            if (id != docente.DocenteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(docente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocenteExists(docente.DocenteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CursoID"] = new SelectList(_context.Cursos, "CursoID", "CursoID", docente.CursoID);
            return View(docente);
        }

        // GET: Docente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var docente = await _context.Docentes
                .Include(d => d.Curso)
                .FirstOrDefaultAsync(m => m.DocenteID == id);
            if (docente == null)
            {
                return NotFound();
            }

            return View(docente);
        }

        // POST: Docente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var docente = await _context.Docentes.FindAsync(id);
            _context.Docentes.Remove(docente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocenteExists(int id)
        {
            return _context.Docentes.Any(e => e.DocenteID == id);
        }
    }
}

CursoMVC/Views/Docente/Create.cshtml
@model CursoMVC.Models.Docente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Docente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DocenteDNI" class="control-label"></label>
                <input asp-for="DocenteDNI" class="form-control" />
                <span asp-validation-for="DocenteDNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class ="form-control" asp-items="ViewBag.CursoID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Docente/Delete.cshtml
@model CursoMVC.Models.Docente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Docente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocenteDNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocenteDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso.CursoID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DocenteID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CursoMVC/Views/Docente/Details.cshtml
@model CursoMVC.Models.Docente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Docente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocenteDNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocenteDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso.CursoID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DocenteID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CursoMVC/Views/Docente/Edit.cshtml
@model CursoMVC.Models.Docente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Docente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DocenteID" />
            <div class="form-group">
                <label asp-for="DocenteDNI" class="control-label"></label>
                <input asp-for="DocenteDNI" class="form-control" />
                <span asp-validation-for="DocenteDNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class="form-control" asp-items="ViewBag.CursoID"></select>
                <span asp-validation-for="CursoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Docente/Index.cshtml
@model IEnumerable<CursoMVC.Models.Docente>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">LISTADO DE DOCENTES</h1>

<p>
    <a asp-action="Create" class=" btn btn-success">AÑADIR DOCENTE</a>
</p>
<form asp-controller="Docente" asp-action="Index">
    <div class="jumbotron">
        <p><span class="glyphicon glyphicon-search"> </span>  DNI: <input type="text" name="busquedaDocenteDNI" /></p>
        <p> <span class="glyphicon glyphicon-search"> </span>  Apellido: <input type="text" name="busquedaDocente" /></p>

        <input type="submit" class="btn-info" value="Buscar Docente" />
    </div>
</form>
    <table class="table , text-center" style="background-color:whitesmoke;margin-top:20px;">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DocenteDNI)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Curso)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DocenteDNI)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Curso.Titulo)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.DocenteID"><span class="glyphicon glyphicon-edit" style="color:forestgreen;"> </span></a> 
                        <a asp-action="Details" asp-route-id="@item.DocenteID"><span class="glyphicon glyphicon-info-sign" style="color:blue;"> </span></a> 
                        <a asp-action="Delete" asp-route-id="@item.DocenteID"><span class="glyphicon glyphicon-trash" style="color:red;"> </span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>