CursoMVC/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CursoMVC.Models
{
    public class Curso
    {
        [Key]
        public int CursoID { get; set; }
        public string Titulo { get; set; }
        public int Creditos { get; set; }
        public ICollection<Inscripcion> Inscripcion { get; set; }
        public ICollection<Docente> Docente { get; set; }

    }
}

CursoMVC/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursoMVC.Data;
using CursoMVC.Models;

namespace CursoMVC.Controllers
{
    public class CursoController : Controller
    {
        private readonly Contexto _context;

        public CursoController(Contexto context)
        {
            _context = context;
        }

        // GET: Curso
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cursos.ToListAsync());
        }

        // GET: Curso/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos
                .FirstOrDefaultAsync(m => m.CursoID == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // GET: Curso/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Curso/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CursoID,Titulo,Creditos")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Curso/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos.FindAsync(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        // POST: Curso/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CursoID,Titulo,Creditos")] Curso curso)
        {
            if (id != curso.CursoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.CursoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Curso/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos
                .FirstOrDefaultAsync(m => m.CursoID == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // POST: Curso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var curso = await _context.Cursos.FindAsync(id);
            _context.Cursos.Remove(curso);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
            return _context.Cursos.Any(e => e.CursoID == id);
        }
    }
}

CursoMVC/Views/Curso/Create.cshtml
@model CursoMVC.Models.Curso

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Curso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creditos" class="control-label"></label>
                <input asp-for="Creditos" class="form-control" />
                <span asp-validation-for="Creditos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Curso/Delete.cshtml
@model CursoMVC.Models.Curso

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Curso</h4>
    <hr/>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creditos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creditos)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CursoID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CursoMVC/Views/Curso/Details.cshtml
@model CursoMVC.Models.Curso

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Curso</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creditos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creditos)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CursoID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CursoMVC/Views/Curso/Edit.cshtml
@model CursoMVC.Models.Curso

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Curso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CursoID" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creditos" class="control-label"></label>
                <input asp-for="Creditos" class="form-control" />
                <span asp-validation-for="Creditos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursoMVC/Views/Curso/Index.cshtml
@model IEnumerable<CursoMVC.Models.Curso>

@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-bottom: 20px;">LISTADO DE CURSOS</h1>

<p>
    <a asp-action="Create"class=" btn btn-success">AÑADIR CURSO</a>
</p>
<form asp-controller="Curso" asp-action="Index">
    <div class="jumbotron">
        
        <p> <span class="glyphicon glyphicon-search"> </span>  Curso: <input type="text" name="busquedaCurso" /></p>

        <input type="submit" class="btn-info" value="Buscar Curso" />
    </div>
</form>

    <table class="table , text-center" style="background-color:whitesmoke;margin-top:20px;">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
                
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Titulo)
                    </td>
                    
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.CursoID"><span class="glyphicon glyphicon-edit" style="color:forestgreen;"> </span></a> 
                        <a asp-action="Details" asp-route-id="@item.CursoID"><span class="glyphicon glyphicon-info-sign" style="color:blue;"> </span></a> 
                        <a asp-action="Delete" asp-route-id="@item.CursoID"><span class="glyphicon glyphicon-trash" style="color:red;"> </span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    